plugin:
    name: 'holgerbaumann.simplecontact::lang.plugin.name'
    description: 'holgerbaumann.simplecontact::lang.plugin.description'
    author: HolgerBaumann
    icon: oc-icon-envelope
    homepage: ''
permissions:
    holgerbaumann.simplecontact.inbox:
        tab: 'holgerbaumann.simplecontact::lang.simplecontact.permission'
        label: 'holgerbaumann.simplecontact::lang.simplecontact.permission_messages'
    holgerbaumann.simplecontact.manage_settings:
        tab: 'holgerbaumann.simplecontact::lang.simplecontact.permission'
        label: 'holgerbaumann.simplecontact::lang.simplecontact.permission_settings'


