plugin:
    name: 'holgerbaumann.communicate::lang.plugin.name'
    description: 'holgerbaumann.communicate::lang.plugin.description'
    author: HolgerBaumann
    icon: oc-icon-envelope
    homepage: ''
permissions:
    holgerbaumann.communicate.inbox:
        tab: 'holgerbaumann.communicate::lang.communicate.permission'
        label: 'holgerbaumann.communicate::lang.communicate.permission_messages'
    holgerbaumann.communicate.manage_settings:
        tab: 'holgerbaumann.communicate::lang.communicate.permission'
        label: 'holgerbaumann.communicate::lang.communicate.permission_settings'


