title: SimpleContact
modelClass: HolgerBaumann\SimpleContact\Models\SimpleContact
list: $/holgerbaumann/simplecontact/models/simplecontact/columns.yaml
recordUrl: holgerbaumann/simplecontact/simplecontact/view/:id
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
defaultSort: 'created_at: desc'
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
