title: Communicate
modelClass: HolgerBaumann\Communicate\Models\Communicate
list: $/holgerbaumann/communicate/models/communicate/columns.yaml
recordUrl: holgerbaumann/communicate/communicate/view/:id
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
defaultSort: 'created_at: desc'
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
