list: $/holgerbaumann/communicate/models/communicateblock/columns.yaml
modelClass: HolgerBaumann\Communicate\Models\Communicateblock
title: Communicateblock
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'holgerbaumann/communicate/communicateblock/update/:id'
