name: Communicateblock
form: $/holgerbaumann/communicate/models/communicateblock/fields.yaml
modelClass: HolgerBaumann\Communicate\Models\Communicateblock
defaultRedirect: holgerbaumann/communicate/communicateblock
create:
    redirect: 'holgerbaumann/communicate/communicateblock/update/:id'
    redirectClose: holgerbaumann/communicate/communicateblock
update:
    redirect: holgerbaumann/communicate/communicateblock
    redirectClose: holgerbaumann/communicate/communicateblock
